support create recurring event
haanhduclinh/viewpoint pull request #5
Opened 2023-05-12 08:48 UTC by leedrum

2023-05-15 08:14 UTC, haanhduclinh requested changes

2023-05-15 08:14 UTC, haanhduclinh commented on lib/ews/soap/builders/ews_builder.rb
> +    def relative_yearly_recurrence!(item)
? I think function name should be
```ruby
def relative_monthly_recurrence
```

2023-05-15 08:14 UTC, haanhduclinh commented on lib/ews/soap/builders/ews_builder.rb
> +      nbuild[NS_EWS_TYPES].absoluteYearly {
is that valid xml request? could you please give me url of document?

2023-05-15 08:14 UTC, haanhduclinh commented on lib/ews/soap/builders/ews_builder.rb
> +      nbuild[NS_EWS_TYPES].AbsoluteMonthRecurrence {
do you mean this field? [AbsoluteMonthlyRecurrence](https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/absolutemonthlyrecurrence)

2023-05-15 08:14 UTC, haanhduclinh commented on lib/ews/soap/builders/ews_builder.rb
> +    def month!(month) # ex: 1..12
[Q] I saw the document. This filed only accept text [Month (Item Recurrence)](https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/month-item-recurrence). can we use number in it?

2023-05-15 08:14 UTC, haanhduclinh commented on lib/ews/soap/builders/ews_builder.rb
> +      nbuild[NS_EWS_TYPES].IsRecurring(boolean.upcase)
[IMO]
```
boolean.to_s.upcase
```

2023-05-15 09:15 UTC, leedrum commented on lib/ews/soap/builders/ews_builder.rb
> +    def relative_yearly_recurrence!(item)
it's should be `relative_yearly_recurrence `

2023-05-15 09:17 UTC, leedrum commented on lib/ews/soap/builders/ews_builder.rb
> +    def month!(month) # ex: 1..12
fixed. using `Date::MONTHNAMES[month.to_i]`

2023-05-16 08:01 UTC, haanhduclinh approved these changes
LGTM!

2023-05-16 08:02 UTC, merged